<?php

echo "<h1>Hello World</h1>";

// echo PHP_EOL;

// echo $this->tag->linkTo(
//     'signup',
//     'Sign Up Here!'
// );
// echo $this->tag->linkTo(
//     'login',
//     ' login Here!'
// );
// if ($users->count() > 0) 
{
    ?>
    <!-- <table class="table table-bordered table-hover"> -->
        <thead class="thead-light">
        <!-- <tr> -->
            <!-- <th>#</th>
            <th>Name</th>
            <th>Email</th>
            <th>Description</th> -->
            <!-- <th>Password</th> -->
            <!-- <th>Action</th> -->
        <!-- </tr>
        </thead>
        <tfoot>
        <tr> -->
            <!-- <td colspan="3">Users quantity: <?php //echo $users->count(); ?></td> -->
        <!-- </tr>
        </tfoot>
        <tbody> -->
        <?php //foreach ($users as $user) { ?>
            
            <!-- <tr> -->
                <td><?php //echo $user->id; ?></td>
                <td><?php //echo $user->name; ?></td>
                <td><?php //echo $user->email; ?></td>
                <td><?php //echo $user->description; ?></td>
                <td><?php //echo $user->password; ?></td>
                <td><?php //echo $this->tag->linkTo([
                        //'edit/edit/'.$user->id,
                        //'Edit', 'class' => 'btn btn-primary' ]);?>
                <?php //echo $this->tag->linkTo([
                        //'index/delete/'.$user->id,
                        //'Delete', 'class' => 'btn btn-danger' ]);?></td>

            <!-- </tr> -->
        <?php
        ?>
        </tbody>
    </table>
    <?php
}